// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BMCD_MCMC
List BMCD_MCMC(arma::mat obs_dist, arma::mat init_X, const int G, double init_sigmasq, const int iters, int modelIndex);
RcppExport SEXP _BMCDcpp_BMCD_MCMC(SEXP obs_distSEXP, SEXP init_XSEXP, SEXP GSEXP, SEXP init_sigmasqSEXP, SEXP itersSEXP, SEXP modelIndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type obs_dist(obs_distSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type init_X(init_XSEXP);
    Rcpp::traits::input_parameter< const int >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type init_sigmasq(init_sigmasqSEXP);
    Rcpp::traits::input_parameter< const int >::type iters(itersSEXP);
    Rcpp::traits::input_parameter< int >::type modelIndex(modelIndexSEXP);
    rcpp_result_gen = Rcpp::wrap(BMCD_MCMC(obs_dist, init_X, G, init_sigmasq, iters, modelIndex));
    return rcpp_result_gen;
END_RCPP
}
// distRcpp
Rcpp::NumericMatrix distRcpp(const NumericMatrix X);
RcppExport SEXP _BMCDcpp_distRcpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(distRcpp(X));
    return rcpp_result_gen;
END_RCPP
}
// bmdsMCMC
extern "C" SEXP bmdsMCMC(SEXP DIST, SEXP p, int nwarm, int niter);
RcppExport SEXP _BMCDcpp_bmdsMCMC(SEXP DISTSEXP, SEXP pSEXP, SEXP nwarmSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type DIST(DISTSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type nwarm(nwarmSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    rcpp_result_gen = Rcpp::wrap(bmdsMCMC(DIST, p, nwarm, niter));
    return rcpp_result_gen;
END_RCPP
}
// dmvnrm_arma_fast
arma::vec dmvnrm_arma_fast(arma::mat const& x, arma::rowvec const& mean, arma::mat const& sigma, bool const logd);
RcppExport SEXP _BMCDcpp_dmvnrm_arma_fast(SEXP xSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP logdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat const& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::rowvec const& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool const >::type logd(logdSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnrm_arma_fast(x, mean, sigma, logd));
    return rcpp_result_gen;
END_RCPP
}
// rdirichlet_cpp
arma::mat rdirichlet_cpp(int num_samples, arma::vec alpha_m);
RcppExport SEXP _BMCDcpp_rdirichlet_cpp(SEXP num_samplesSEXP, SEXP alpha_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_samples(num_samplesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha_m(alpha_mSEXP);
    rcpp_result_gen = Rcpp::wrap(rdirichlet_cpp(num_samples, alpha_m));
    return rcpp_result_gen;
END_RCPP
}
// Arma_colSums
arma::rowvec Arma_colSums(const arma::mat& x);
RcppExport SEXP _BMCDcpp_Arma_colSums(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Arma_colSums(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BMCDcpp_BMCD_MCMC", (DL_FUNC) &_BMCDcpp_BMCD_MCMC, 6},
    {"_BMCDcpp_distRcpp", (DL_FUNC) &_BMCDcpp_distRcpp, 1},
    {"_BMCDcpp_bmdsMCMC", (DL_FUNC) &_BMCDcpp_bmdsMCMC, 4},
    {"_BMCDcpp_dmvnrm_arma_fast", (DL_FUNC) &_BMCDcpp_dmvnrm_arma_fast, 4},
    {"_BMCDcpp_rdirichlet_cpp", (DL_FUNC) &_BMCDcpp_rdirichlet_cpp, 2},
    {"_BMCDcpp_Arma_colSums", (DL_FUNC) &_BMCDcpp_Arma_colSums, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_BMCDcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
