// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BMCD_MCMC
List BMCD_MCMC(arma::mat obs_dist, arma::mat init_X, const int G, double init_sigmasq, const int burn, const int iters, int modelIndex);
RcppExport SEXP _BMCDcpp_BMCD_MCMC(SEXP obs_distSEXP, SEXP init_XSEXP, SEXP GSEXP, SEXP init_sigmasqSEXP, SEXP burnSEXP, SEXP itersSEXP, SEXP modelIndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type obs_dist(obs_distSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type init_X(init_XSEXP);
    Rcpp::traits::input_parameter< const int >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type init_sigmasq(init_sigmasqSEXP);
    Rcpp::traits::input_parameter< const int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const int >::type iters(itersSEXP);
    Rcpp::traits::input_parameter< int >::type modelIndex(modelIndexSEXP);
    rcpp_result_gen = Rcpp::wrap(BMCD_MCMC(obs_dist, init_X, G, init_sigmasq, burn, iters, modelIndex));
    return rcpp_result_gen;
END_RCPP
}
// distRcpp
Rcpp::NumericMatrix distRcpp(const NumericMatrix X);
RcppExport SEXP _BMCDcpp_distRcpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(distRcpp(X));
    return rcpp_result_gen;
END_RCPP
}
// bmdsMCMC
extern "C" SEXP bmdsMCMC(SEXP DIST, SEXP p, int nwarm, int niter);
RcppExport SEXP _BMCDcpp_bmdsMCMC(SEXP DISTSEXP, SEXP pSEXP, SEXP nwarmSEXP, SEXP niterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type DIST(DISTSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type nwarm(nwarmSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    rcpp_result_gen = Rcpp::wrap(bmdsMCMC(DIST, p, nwarm, niter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BMCDcpp_BMCD_MCMC", (DL_FUNC) &_BMCDcpp_BMCD_MCMC, 7},
    {"_BMCDcpp_distRcpp", (DL_FUNC) &_BMCDcpp_distRcpp, 1},
    {"_BMCDcpp_bmdsMCMC", (DL_FUNC) &_BMCDcpp_bmdsMCMC, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_BMCDcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
