# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BMCD_MCMC <- function(obs_dist, init_X, G, init_sigmasq, burn, iters, modelIndex) {
    .Call(`_BMCDcpp_BMCD_MCMC`, obs_dist, init_X, G, init_sigmasq, burn, iters, modelIndex)
}

distRcpp <- function(X) {
    .Call(`_BMCDcpp_distRcpp`, X)
}

bmdsMCMC <- function(DIST, p, nwarm = 1000L, niter = 5000L) {
    .Call(`_BMCDcpp_bmdsMCMC`, DIST, p, nwarm, niter)
}

